#!/bin/bash

# $1 Input file to start from.
#    Values will be overwritten if necessary.
# $2 File with parameters to scan
#    Format: ecut 40 80 120\n  ngkpt *2 *4 *8\n

# name of shell script
ME=$(basename "$0")

# prints for error messages
SYNTAX="Syntaxis: ${ME} BASE SCAN [FILE]"
UNREAD="${ME}: COULD NOT OPEN"

# Transform long options to short ones
for arg in "$@"; do
  shift
  case "$arg" in
    "--help" | "-help")   set -- "$@" "-h" ;;
    *)                    set -- "$@" "$arg"
  esac
done

# try to handle the options
while getopts ":h" opt; do
  case "${opt}" in
    h ) echo "${SYNTAX}"
        exit 0
        ;;
    \?) echo "${SYNTAX}" 1>&2
        exit 1
  esac
done
shift "$((OPTIND - 1))"

# check parameters
if [ "${#}" -ne 3 -a "${#}" -ne 2 ]
then
  echo "${SYNTAX}" 1>&2
  exit 1
else
  # set the variables
  BASE="${1}"
  SCAN="${2}"
  FILE="${3}"
  for VAR in "${BASE}" "${SCAN}" "${FILE}"
  do
    if [ ! -r "${VAR}" ]
    then
      echo "${UNREAD} ${VAR}" 1>&2
      exit 2
    fi
  done
fi

# destination of the scan results
DEST="./results${$}"

# open scan
exec 3< "${SCAN}"  # for keys filtering
exec 4< "${SCAN}"  # for directory generation

# prepare destiny
mkdir "${DEST}"
cp "${BASE}" "${DEST}"
# go to destiny
cd "${DEST}"
# create template
TEMP=${BASE##*/}
echo -e "\n# SCANNING:" >> "${TEMP}"

# set first
FIRST='true'

# for all lines in scan
while read LINE 0<&3
do
  # parse line
  KEY="${LINE%% *}"
  # remove key from template
  sed -i "/${KEY}/d" "${TEMP}"
done

# for all lines in scan
while read LINE 0<&4
do
  # parse line
  KEY="${LINE%% *}"
  ARGS=(${LINE#* })
  
  # provide directories for the args
  if [ ${FIRST} = 'true' ]
   then
    # initialize
    for OPT in "${ARGS[@]}"
    do
      mkdir "${OPT}"
      # copy the file if there is one
      if [ ! -z "${FILE}" ]
      then
        cp ../"${FILE}" "${OPT}"
      fi
      cp "${TEMP}" "${OPT}"
      # add the relevant variable
      echo "${KEY} ${OPT}" >> "${OPT}"/"${TEMP}"
    done
    FIRST='false'
  else
    # multiply the existing directories
    RANGE="$(find . -type d | grep -v '^.$' | xargs echo)"
    for DIR in ${RANGE} 
    do
      for OPT in "${ARGS[@]}"
      do
        NEW="${DIR}_${OPT}"
        cp -r ${DIR} "${NEW}"
        cp "${DIR}"/"${TEMP}" "${NEW}"/"${TEMP}"
        # add the relevant variable
        echo "${KEY} ${OPT}" >> "${NEW}"/"${TEMP}"
      done
      rm -r "${DIR}"
    done
  fi
done

# remove template
rm "${TEMP}"

# close file descriptors
exec 3<&-
exec 4<&-

exit 0

